basePath: /
definitions:
  abstraction.PaginationInfo:
    properties:
      count:
        type: integer
      more_records:
        type: boolean
      page:
        type: integer
      page_size:
        type: integer
      sort:
        type: string
      sort_by:
        type: string
    type: object
  dto.AuthLoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  dto.AuthLoginResponse:
    properties:
      created_at:
        type: string
      created_by:
        type: string
      email:
        type: string
      id:
        type: integer
      is_active:
        type: boolean
      modified_at:
        type: string
      modified_by:
        type: string
      name:
        type: string
      orders:
        description: relations
        items:
          $ref: '#/definitions/model.OrderEntityModel'
        type: array
      password:
        type: string
      phone:
        type: string
      role:
        type: string
      token:
        type: string
    required:
    - email
    - is_active
    - name
    - password
    - phone
    - role
    type: object
  dto.AuthLoginResponseDoc:
    properties:
      body:
        properties:
          data:
            $ref: '#/definitions/dto.AuthLoginResponse'
          meta:
            $ref: '#/definitions/response.Meta'
        type: object
    type: object
  dto.AuthRegisterRequest:
    properties:
      email:
        type: string
      is_active:
        type: boolean
      name:
        type: string
      password:
        type: string
      phone:
        type: string
      role:
        type: string
    required:
    - email
    - is_active
    - name
    - password
    - phone
    - role
    type: object
  dto.AuthRegisterResponse:
    properties:
      created_at:
        type: string
      created_by:
        type: string
      email:
        type: string
      id:
        type: integer
      is_active:
        type: boolean
      modified_at:
        type: string
      modified_by:
        type: string
      name:
        type: string
      orders:
        description: relations
        items:
          $ref: '#/definitions/model.OrderEntityModel'
        type: array
      password:
        type: string
      phone:
        type: string
      role:
        type: string
    required:
    - email
    - is_active
    - name
    - password
    - phone
    - role
    type: object
  dto.AuthRegisterResponseDoc:
    properties:
      body:
        properties:
          data:
            $ref: '#/definitions/dto.AuthRegisterResponse'
          meta:
            $ref: '#/definitions/response.Meta'
        type: object
    type: object
  model.OrderEntityModel:
    properties:
      code:
        type: string
      created_at:
        type: string
      created_by:
        type: string
      id:
        type: integer
      modified_at:
        type: string
      modified_by:
        type: string
      order_items:
        items:
          $ref: '#/definitions/model.OrderItemEntityModel'
        type: array
      user_id:
        description: relations
        type: integer
    required:
    - code
    type: object
  model.OrderItemEntityModel:
    properties:
      code:
        type: string
      created_at:
        type: string
      created_by:
        type: string
      id:
        type: integer
      modified_at:
        type: string
      modified_by:
        type: string
      order_id:
        description: relations
        type: integer
      product_id:
        type: integer
    required:
    - code
    type: object
  response.Meta:
    properties:
      info:
        $ref: '#/definitions/abstraction.PaginationInfo'
      message:
        default: "true"
        type: string
      success:
        default: true
        type: boolean
    type: object
  response.errorResponse:
    properties:
      error:
        type: string
      meta:
        $ref: '#/definitions/response.Meta'
    type: object
host: localhost:3030
info:
  contact: {}
  description: This is a doc for gank-ecommerce-auth.
  title: gank-ecommerce-auth
  version: 0.0.1
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Login user
      parameters:
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.AuthLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.AuthLoginResponseDoc'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.errorResponse'
      summary: Login user
      tags:
      - auth
  /register:
    post:
      consumes:
      - application/json
      description: Register user
      parameters:
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.AuthRegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.AuthRegisterResponseDoc'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.errorResponse'
      security:
      - BearerAuth: []
      summary: Register user
      tags:
      - auth
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
