version: "3.9"
services:
  postgres:
    container_name: postgres01
    image: postgres:12-alpine
    environment: 
      - POSTGRES_USER=gank_ecommerce
      - POSTGRES_PASSWORD=f72d8509-c70a-485a-a471-23f899b988ab
      - POSTGRES_DB=gank_ecommerce_db
    ports:
      - "5432:5432"
    networks:
      - postgres-net
  
networks:
  postgres-net:
    name: postgres_net